### ISSUE TITLE
Reset views?

### ISSUE THREAD

**Issue by ParitoshBh** [iammert/MaterialIntroView#10]
A quick look at code did reveal that there's a way to reset preferences but I am not sure if there exists any such method? How do I reset the tips view, as in let's say I want to show it more than once.

Oh and this is by far the most useful library for showing helpful tips. Kudos :+1:

**Comment by iammert** [comment]
Actually you can reset specific preference or all preferences.
```
PreferencesManager pref = new PreferencesManager(this);
pref.reset("VIEW_ID");
pref.resetAll();
```
