### ISSUE TITLE
Give focus to the drawer view

### ISSUE THREAD

**Issue by OneManStudioDotSe** [iammert/MaterialIntroView#13]
I am trying to give the focus to the drawer view, just like at the first screenshot that you have at the "Demos" set of images.
There is no example like that in the sample project. How did you accomplish that?

**Comment by behzodbek** [comment]
How can I select certain menu item?

**Comment by iammert** [comment]
@OneManStudioDotSe I will add this to sample asap. But you can achieve by following snippet.
```
private View getDrawerView(Toolbar toolbar) {
        for (int i = 0; i < toolbar.getChildCount(); i++) {
            if (toolbar.getChildAt(i) instanceof ImageButton)
                return toolbar.getChildAt(i);
        }
        return null;
    }
```

Give toolbar as a parameter.

**Comment by marlborock** [comment]
Toolbar has 2 ImageButton (mNavButtonView,mCollapseButtonView)

try with reflection

Field field = Toolbar.class.getDeclaredField("mNavButtonView");
field.setAccessible(true);
view = (ImageButton)field.get(toolbar);

**Comment by DJafari** [comment]
i'm using this function to get humberger view of toolbar :

```java
public static View getToolbarNavigationIcon(Toolbar toolbar){
        boolean hadContentDescription = TextUtils.isEmpty(toolbar.getNavigationContentDescription());
        String contentDescription = !hadContentDescription ? toolbar.getNavigationContentDescription().toString() : "navigationIcon";
        toolbar.setNavigationContentDescription(contentDescription);
        ArrayList<View> potentialViews = new ArrayList<>();
        toolbar.findViewsWithText(potentialViews,contentDescription, View.FIND_VIEWS_WITH_CONTENT_DESCRIPTION);
        View navIcon = null;
        if(potentialViews.size() > 0){
            navIcon = potentialViews.get(0);
        }
        if(hadContentDescription)
            toolbar.setNavigationContentDescription(null);
        return navIcon;
    }
```

**Comment by DJafari** [comment]
@behzodbek just find view by menu item id, sample in activity :

```java
View favoriteItemView = findViewById(R.id.fav);
```

**Comment by iammert** [comment]
@DJafari actually your code seems like doing same thing with mine. You get index 0 if list is not empty, I get first imagebutton on childlist.

**Comment by iammert** [comment]
@behzodbek If your problem is not solved please create new issue. Because seems like this drawer issue is solved.

**Comment by nextflex** [comment]
Is there any way to focus the ActionBarDrawerToggle at the new ActionBar?

**Comment by amaroukun17** [comment]
hi i just want to ask how can i make view for each navigation item ?
thanks in advance. i'm new to android programming

**Comment by riki-dexter** [comment]
@DJafari 

> just find view by menu item id, sample in activity :

It's not working for me. Can you explain more?
