### ISSUE TITLE
Problem after support 23.2.1

### ISSUE THREAD

**Issue by Zeliret** [iammert/MaterialIntroView#23]
Hi there! 
I've got a problem after an update of the support lib. Info card displays "below" dim area. 

http://www.awesomescreenshot.com/image/1081228/f9cac940ebe6ab75f585011cc3c557b7

**Comment by RafaRuiz** [comment]
@Zeliret did  you solve this? I'm having the same problem

**Comment by badoualy** [comment]
+1 on this

**Comment by badoualy** [comment]
Caused by `CardView` in `material_intro_card`, it should be using attribute `app:cardBackgroundColor` instead of `android:background`

**Comment by badoualy** [comment]
Use my fork commit to fix this
`compile 'com.github.badoualy:MaterialIntroView:e713b6c28a'`
