### ISSUE TITLE
small bug in PreferencesManager

### ISSUE THREAD

**Issue by DJafari** [iammert/MaterialIntroView#4]
please add apply method at the end of this line :

https://github.com/iammert/MaterialIntroView/blob/master/materialintro/src/main/java/co/mobiwise/materialintro/prefs/PreferencesManager.java#L28

and if possible, add method to reshow intro view in library

**Comment by iammert** [comment]
I added resetAll() method to PreferenceManager class. And fixed that small bug.

**Comment by DJafari** [comment]
thanks, please push it maven as 1.3 version

**Comment by iammert** [comment]
Done.
