### ISSUE TITLE
Working with RecyclerView elements

### ISSUE THREAD

**Issue by pedronveloso** [iammert/MaterialIntroView#42]
I don't recall seeing support for recyclerview, so if that's the case I'm here requesting support for that.

**Comment by iammert** [comment]
Actually there is. You check it from here. https://github.com/iammert/MaterialIntroView/commit/be5de5cd17ee64cbef948eb45a74589d1cac9fea

**Comment by pedronveloso** [comment]
It's actually pretty simple, just getting the `childAt` element. It works, thank you ;)
