### ISSUE TITLE
How to set focus on hamburger icon?

### ISSUE THREAD

**Issue by rgc10** [iammert/MaterialIntroView#43]
I want to set focus on the hamburger icon like you've shown in the image(shown below).

![art_drawer](https://cloud.githubusercontent.com/assets/15252460/16855309/61221f3a-4a32-11e6-94e2-46dcfdbe4e25.png)

 But it's not possible since i can't get a view reference of the icon. I'm using the following code: 

` DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
 ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();`

Since the `setTarget()` method needs a view as a paramater, do i need to set up the hamburger icon on the toolbar in xml so that i can get a view reference from it or is there another way to do it?

**Comment by iammert** [comment]
Here is the closed issue about that one.https://github.com/iammert/MaterialIntroView/issues/13

**Comment by rgc10** [comment]
Thank you so much!
