### ISSUE TITLE
outofmemory issue

### ISSUE THREAD

**Issue by DJafari** [iammert/MaterialIntroView#5]
https://github.com/iammert/MaterialIntroView/blob/master/materialintro/src/main/java/co/mobiwise/materialintro/view/MaterialIntroView.java#L400

why view not removed after dismiss ?

this is caused outofmemory for multiple MaterialIntroView

**Comment by iammert** [comment]
I think it is because of I used View.INVISIBLE instead of View.GONE. I will fix this.

**Comment by iammert** [comment]
Can you try this dependency. 

`    compile 'com.github.iammert:MaterialIntroView:a4b7947d19'`

**Comment by DJafari** [comment]
yes problem is INVISIBLE, but i think removeView after dismiss needed

**Comment by iammert** [comment]
I think this is fixed on version 1.4 :) try it and give me feedback please :)

**Comment by DJafari** [comment]
solved ! thanks
